# MariaDB \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC124\uC815
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/school_chat
spring.datasource.username=school-chat
spring.datasource.password=qwerasdf123@

# JPA \uC124\uC815
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# HikariCP \uC124\uC815 (Connection Pool)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# SQL \uB85C\uADF8 \uD3EC\uB9F7 (SQL \uBCF4\uAE30 \uC88B\uAC8C \uD45C\uC2DC)
spring.jpa.properties.hibernate.format_sql=true

# \uD0C0\uC784\uB9AC\uD504 \uC124\uC815
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.web.resources.add-mappings=true
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/


# \uCE90\uC2DC \uBE44\uD65C\uC131\uD654
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true